# -*- coding: utf-8 -*-
"""Task 1 Internship

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zbDh1NJxSDTvgj--_MXm3Tel1aVMJdb7
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/Global_Superstore(CSV).csv")
df

plt.rcParams['figure.figsize']=(20,8)
plt.bar (df['Sub-Category'],df['Sales'])
plt.rcParams.update({'font.size':10})
plt.xlabel('Sub_Cateroty')
plt.ylabel('Sales')
plt.show()